# Generated by Django 2.2.7 on 2019-11-06 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DAC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50)),
                ('weight', models.FloatField(verbose_name='Вес')),
                ('have_minijack', models.BooleanField()),
                ('dac', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='phones.DAC')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='phones.Manufacturer')),
            ],
        ),
        migrations.AddField(
            model_name='dac',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='phones.Manufacturer'),
        ),
    ]
