# Generated by Django 2.2.7 on 2019-11-08 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_auto_20191107_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operatingsystem',
            options={'verbose_name': 'Операционная система', 'verbose_name_plural': 'Операционные системы'},
        ),
        migrations.AlterModelOptions(
            name='operatingsystemvendor',
            options={'verbose_name': 'Разработчик ОС', 'verbose_name_plural': 'Разработчики ОС'},
        ),
        migrations.AddField(
            model_name='phone',
            name='battery_capacity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Емкость батареи'),
        ),
        migrations.AddField(
            model_name='phone',
            name='bluetooth_supported_versions',
            field=models.FloatField(choices=[(1.0, '1.0'), (2.0, '2.0'), (3.0, '3.0'), (4.0, '4.0'), (4.1, '4.1'), (4.2, '4.2'), (5.0, '5.0')], null=True, verbose_name='Максимальная версия Bluetooth'),
        ),
        migrations.AddField(
            model_name='phone',
            name='has_quick_charge',
            field=models.BooleanField(default=False, verbose_name='Быстрая зарядка'),
        ),
        migrations.AddField(
            model_name='phone',
            name='is_battery_removable',
            field=models.BooleanField(default=False, verbose_name='Съемная батарея'),
        ),
        migrations.AddField(
            model_name='phone',
            name='quick_charge_technology',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='wifi_supported_versions',
            field=models.CharField(choices=[('802.11n', 'Wi-Fi 802.11 b/g/n'), ('802.11ac', 'Wi-Fi 802.11 a/b/g/n/ac'), ('802.11ax', 'Wi-Fi 802.11 a/b/g/n/ac/ax')], max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='SoC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('code', models.CharField(db_index=True, max_length=20)),
                ('process_technology', models.PositiveSmallIntegerField(verbose_name='Техпроцесс')),
                ('cpu', models.CharField(max_length=150)),
                ('cpu_bits', models.PositiveSmallIntegerField(choices=[(32, '32 bit'), (64, '64 bit')], verbose_name='Архитектура процессора')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='phones.Manufacturer')),
            ],
            options={
                'verbose_name': 'Система на кристалле',
                'verbose_name_plural': 'Системы на кристалле',
            },
        ),
        migrations.AddField(
            model_name='phone',
            name='soc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='phones.SoC'),
        ),
    ]
