# Generated by Django 2.2.7 on 2019-11-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_auto_20191108_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayResolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveSmallIntegerField(verbose_name='Высота')),
                ('width', models.PositiveSmallIntegerField(verbose_name='Ширина')),
            ],
        ),
        migrations.AddConstraint(
            model_name='displayresolution',
            constraint=models.UniqueConstraint(fields=('height', 'width'), name='unique_display_resolution'),
        ),
    ]
