# Generated by Django 2.2.7 on 2019-11-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0004_auto_20191108_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='displayresolution',
            options={'verbose_name': 'Разрешение экрана', 'verbose_name_plural': 'Список разрешений экрана'},
        ),
        migrations.AddField(
            model_name='displayresolution',
            name='ratio',
            field=models.CharField(default='16:9', max_length=8, verbose_name='Соотношение сторон'),
        ),
    ]
