# Generated by Django 2.2.7 on 2019-11-08 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0005_auto_20191108_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='display_resolution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='phones.DisplayResolution', verbose_name='Разрешение экрана'),
        ),
    ]
