# Generated by Django 2.2.7 on 2019-11-08 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0007_auto_20191108_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='displaytechnology',
            options={'verbose_name': 'Технология дисплея', 'verbose_name_plural': 'Технологии дисплея'},
        ),
        migrations.AlterField(
            model_name='phone',
            name='display_resolution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='phones.DisplayResolution', verbose_name='Разрешение экрана'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='display_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='phones.DisplayTechnology'),
        ),
    ]
